name: RDP
on:
  
  workflow_dispatch:

jobs:
  interactive:
    runs-on: ubuntu-22.04
    steps:     
      - name: 
        run: |
              curl https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/scripts/no.sh | sudo bash 
              
  
