name: RDP
on:
  push:
  workflow_dispatch:

jobs:
  interactive:
    runs-on: ubuntu-latest  
    steps:     
      - name: 
        run: |
             printf "root\nroot" | sudo passwd root && printf "root" | su - root -c " \
             pip install jprq && jprq tcp 22 &>>cat.txt & "
             printf "root\nroot" | sudo passwd root && printf "root" | su - root -c " \
             while :; do cat cat.txt ; sleep 2 ; done "
