name: RDP
on:
  
  workflow_dispatch:

jobs:
  interactive:
    runs-on: ubuntu-latest
    steps:     
      - name: 
        run: |
              #curl https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/scripts/tty.sh | sudo bash 
              npm install -g localtunnel
              lt -p 8000 >> cat.txt &
              pip install termpair 
              termpair serve &
              while :; do cat cat.txt ; sleep 2 ; done
              
                                       

  
